name: .NET

on:
  push:
    branches: [ master,mihir-gautam-patch-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: ./publish
      
